### ISSUE TITLE
Question regarding support for this page

### ISSUE THREAD

**Issue by LukePrior** [atye/wikitable-api#34]
Hello,

I am attempting to use your API on this specific page: https://en.wikipedia.org/wiki/Opinion_polling_for_the_2022_Australian_federal_election
I have tried: https://www.wikitable2json.com/api/Opinion_polling_for_the_2022_Australian_federal_election but this does not work.

I can get the raw data from the table using: https://en.wikipedia.org/w/api.php?action=parse&page=Opinion_polling_for_the_2022_Australian_federal_election&section=2&contentmodel=wikitext&prop=wikitext&format=json

Does your API allow me to get that same data but as a processed json file?

**Comment by atye** [comment]
@LukePrior 

This page isn't working because the table has HTML class `toccolours` but this API is only checking for tables with classes `wikitable` or `standard`.

I wasn't aware of the `toccolours` class until you opened this. I will see if this type of table can be supported.

**Comment by atye** [comment]
@LukePrior 

This should be working now.

**Comment by LukePrior** [comment]
Cheers I appreciate it.

**Comment by LukePrior** [comment]
This produces an error: https://www.wikitable2json.com/api/Opinion_polling_for_the_2022_Australian_federal_election?lang=en&format=keyValue

**Comment by atye** [comment]
I'll look into this.

**Comment by atye** [comment]
@LukePrior

The keyValue format should work for the first table now. 

https://www.wikitable2json.com/api/Opinion_polling_for_the_2022_Australian_federal_election?lang=en&format=keyValue&table=0

However, the keyValue format is simple and uses the first row as keys. The 2nd row and onwards are the data rows. This particular table is complex and it looks like some of the 2nd row should be used as keys. The keyValue format doesn't account for this and I have no plans to change it because realistically there is no way to know how to process any specific table. The keyValue format is just a helper for simpler tables.

With the matrix format, you can process the returned JSON however you like which is the main purpose of the API.

Another note about this page:

You will get an error on the 3rd table (table index 2) if you try to use the keyValue format for the whole page. There is a column span value that is inflating a row length.


```
<tr>
 <th>5 October 2021</th>
 <td colspan="12"><b><a href="/wiki/Gladys_Berejiklian" title="Gladys Berejiklian">Gladys Berejiklian</a> resigns as Premier of New South Wales</b></td>
</tr>
```

The first row (keys) have 10 columns but the above span is for 12 columns. I consider this a formatting issue with the table itself and not an issue with the API. The colspan value should probably be 9 but that is not up to me to decide.

**Comment by LukePrior** [comment]
Hi, not all of the data from the table seems to be included, specifically the sub-columns for the primary and 2pp votes. 

I'm not entirely sure what the best approach would be to solve this maybe combine all the data from the nested columns into one?

Or you could determine the keys by working your way down the rows until you have reached all the nested columns. You could generate the key names by combining all the parent names of the nested columns.

This would give you Primary vote L/NP, Primary vote ALP, etc.

**Comment by atye** [comment]
With the keyValue format, you are correct. It doesn't account for any sub-columns as keys; only the first row. This table is too complex for that. 

Coming up with an algorithm to determine the correct keys for this table, and all other tables on any Wikipedia page, sounds very difficult. These tables are not unique and can be formatted and styled in many different ways. The keys could be anywhere. Maybe it's feasible, but it'd be tough. Right now, I don't have the ambition to come up with something like that.

Since you know exactly what table you are working with and what/where the keys are, you can process the matrix format any way you want; which is my intention with this API.

An example of post-processing can be found at https://github.com/ErenMcLaren/JSON_Chemical_Formulae_Glossary. This person used my API and did a little processing to get the format he wanted.

**Comment by atye** [comment]
As stated above, coming up with a general algorithm to correctly parse key value pairs for any table sounds near impossible. Feel free to open this again if you have questions about this.

**Comment by LukePrior** [comment]
Hey I'm running into some issues with this request: https://www.wikitable2json.com/api/Opinion_polling_for_the_2022_Australian_federal_election?table=0&format=keyValue&lang=en&cleanRef=true

`{"error":"keys length does not match row length","code":500,"details":{"KeysLength":14,"RowLength":13,"RowNumber":1,"TableIndex":0}}`

I've had a look at the table in question and tried making some edits but couldn't make the API happy, any ideas?

**Comment by LukePrior** [comment]
I was also having a think about the sub-column keyValue problem and had a few ideas.

The tables with nested columns will often have other column headers with a rowspan of 2 so this can be used to identify places and then the colspan properties of the header columns can be used to get the appropriate number of child columns. To get the name for these subcolumns just get the header column and prepend it to the nested column.

![image](https://user-images.githubusercontent.com/22492406/163800317-67566f74-4bce-4415-a59b-42f372816ef7.png)

The API will currently only return the two header columns (Primary vote, and 2pp vote) in the above scenario but using this approach it would instead return (Primary vote L/NP, Primary vote ALP, Primary vote GRN, Primary vote ONP, Primary vote UAP, Primary vote OTH, Primary vote UND, 2pp vote L/NP, 2pp vote ALP)

I think this is the most common approach for tables so if this solution is technically feasible I believe it could be a useful addition.

**Comment by atye** [comment]
@LukePrior 

https://www.wikitable2json.com/api/Opinion_polling_for_the_2022_Australian_federal_election?table=0&format=keyValue&lang=en&cleanRef=true doesn't return an error for me. Perhaps you made recently made a change that made it compatible with the keyValue format.

The keyValue format doesn't take `theader` or `th` elements into account. I'll give this some thought and see how it can be done.

**Comment by atye** [comment]
@LukePrior 

In the meantime, processing the matrix output to fit your structure will get you what you want.

**Comment by LukePrior** [comment]
I did make an edit to the page so it might just have taken the cache a while to update. Thanks for looking into the keyvalue thing.
